version: '3.4'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=oracledb==1.1.0
      - POSTGRES_HOST=dwpostgres
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./dbt_nutricao:/usr/local/airflow/dags/dbt/dbt_nutricao:rw
      - ./dbt_suprimentos:/usr/local/airflow/dags/dbt/dbt_suprimentos:rw
      - ./include:/usr/local/airflow/.oracle/instantclient_19_23/
      - ./include:/usr/local/airflow/.postgresql/data/instantclient_17_0/
    healthcheck:
      test: ["CMD", "curl", "https://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      # start_period: 30s
  
  # scheduler:
  #   volumes:
  #     - ./dbt_nutricao:/usr/local/airflow/dags/dbt/dbt_nutricao:rw
  #     - ./dbt_suprimentos:/usr/local/airflow/dags/dbt/dbt_suprimentos:rw
  
  # triggerer:
  #   volumes:
  #     - ./dbt_nutricao:/usr/local/airflow/dags/dbt/dbt_nutricao:rw
  #     - ./dbt_suprimentos:/usr/local/airflow/dags/dbt/dbt_suprimentos:rw

  dwpostgres:
    image: postgres:17rc1-alpine3.19
    restart: unless-stopped
    container_name: dwpronto_postgres
    env_file: ./.env
    ports:
      - "5434:5432"
    volumes:
        - postgres-volume:/usr/local/airflow/.postgresql/data
      # - postgres-volume:/var/lib/postgresql/data
    depends_on:
      - webserver
    networks:
      - airflow


volumes:
  postgres-volume:


networks:
  airflow:
    driver: bridge